version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker-builds/flask-dev-dockerfile
    
    volumes:
      - ./src:/app/src:ro
      - ./settings.toml:/app/settings.toml:ro

    environment:
      - FLASK_APP=src
      - FLASK_ENV=development

    ports:
      - 5000:5000

    networks:
      - cache
      - db

  redis:
    image: redis
    networks:
      - cache

  mongodb:
    image: bitnami/mongodb:latest
    networks:
      - db

networks:
  cache:
  db:

